In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (accuracy_score,confusion_matrix)
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.cluster import KMeans
%matplotlib inline

#Vaikuttaa kaavioiden ulkoasuun:
sns.set()

In [2]:
df=pd.read_excel('http://taanila.fi/wine.xlsx')
df.rename(columns={'Y':'Viini'}, inplace=True)
df.head()

Viini     X1    X2    X3    X4   X5    X6    X7    X8    X9   X10   X11  \
0      1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04   
1      1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05   
2      1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03   
3      1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86   
4      1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04   

    X12   X13  
0  3.92  1065  
1  3.40  1050  
2  3.17  1185  
3  3.45  1480  
4  2.93   735

In [3]:
#Tehdään fature-matriisi,jota varten pudotetaan Y-muuttuja
X = df.drop('Viini', axis=1)

#Tehdään target eli viini
y = df['Viini']

In [4]:
#jaetaan data testidataan ja opetusdataan
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5)

In [5]:
#Sovitetaan opetusdata ja testidata K-nearest neighbors-malliin (KNN)
malli = KNeighborsClassifier(n_neighbors=1)
malli.fit(X_train, y_train)

#Mallin mukaisten ennusteiden laskeminen opetusdatalle ja testidatalle:
y_train_malli = malli.predict(X_train)
y_test_malli = malli.predict(X_test)

In [6]:
#Oikeaan osuneiden ennusteiden osuus datoissa
as_train = accuracy_score(y_train, y_train_malli)
as_test = accuracy_score(y_test, y_test_malli)

#Confusion-matriisit datoille
cm_train = confusion_matrix(y_train, y_train_malli)
cm_test = confusion_matrix(y_test, y_test_malli)

print('Oikeaan osuneiden ennusteiden osuus opetusdatassa = {}'.format(as_train))
print('Confusion-matriisi opetusdatalle = \n {}'.format(cm_train) + "\n")
print('Oikeaan osuneiden ennusteiden osuus testidatassa = {}'.format(as_test))
print('Confusion-matriisi testidatalle = \n {}'.format(cm_test))

Oikeaan osuneiden ennusteiden osuus opetusdatassa = 1.0
Confusion-matriisi opetusdatalle = 
 [[40  0  0]
 [ 0 57  0]
 [ 0  0 36]]

Oikeaan osuneiden ennusteiden osuus testidatassa = 0.7555555555555555
Confusion-matriisi testidatalle = 
 [[15  2  2]
 [ 1 12  1]
 [ 1  4  7]]


Kun naapureiden lukumääräksi määritellään 1, osuu on KNN-malli täydellisesti opetusdatan osalta. Testidatassa se kuitenkin osuu 
vain 75%

In [7]:
#Uusi dataframe
df2=pd.read_excel('http://taanila.fi/wine.xlsx')
df2.rename(columns={'Y':'Viini'}, inplace=True)

In [8]:
#Tehdään fature-matriisi,jota varten pudotetaan Y-muuttuja
X = df2.drop('Viini', axis=1)

#Tehdään target eli viini
y = df2['Viini']

In [9]:
#jaetaan data uudestaan testidataan ja opetusdataan
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5)

In [10]:
#Sovitetaan opetusdata ja testidata Gaussian Naive Bayes-maliin
malli = GaussianNB()
malli.fit(X_train, y_train)

#Mallin mukaisten ennusteiden laskeminen opetusdatalle ja testidatalle:
y_train_malli = malli.predict(X_train)
y_test_malli = malli.predict(X_test)

In [11]:
#Oikeaan osuneiden ennusteiden osuus datoissa
as_train = accuracy_score(y_train, y_train_malli)
as_test = accuracy_score(y_test, y_test_malli)

#Confusion-matriisit datoille
cm_train = confusion_matrix(y_train, y_train_malli)
cm_test = confusion_matrix(y_test, y_test_malli)

print('Oikeaan osuneiden ennusteiden osuus opetusdatassa = {}'.format(as_train))
print('Confusion-matriisi opetusdatalle = \n {}'.format(cm_train) + "\n")
print('Oikeaan osuneiden ennusteiden osuus testidatassa = {}'.format(as_test))
print('Confusion-matriisi testidatalle = \n {}'.format(cm_test))

Oikeaan osuneiden ennusteiden osuus opetusdatassa = 0.9924812030075187
Confusion-matriisi opetusdatalle = 
 [[40  0  0]
 [ 0 56  1]
 [ 0  0 36]]

Oikeaan osuneiden ennusteiden osuus testidatassa = 0.9333333333333333
Confusion-matriisi testidatalle = 
 [[16  3  0]
 [ 0 14  0]
 [ 0  0 12]]


Gaussian Naive Bayes-malli onnistuu ennustamaan opetusdatan lähes täydellisesti ja testidatan melko hyvin: 93% 

In [12]:
#Uusi dataframe
df3=pd.read_excel('http://taanila.fi/wine.xlsx')
df3.rename(columns={'Y':'Viini'}, inplace=True)

In [13]:
#Tehdään fature-matriisi,jota varten pudotetaan Y-muuttuja
X = df3.drop('Viini', axis=1)

#Tehdään target eli viini
y = df3['Viini']

In [14]:
#jaetaan data uudestaan testidataan ja opetusdataan
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5)

In [15]:
#Sovitetaan opetusdata ja testidata logistisen regression malliin
malli = LogisticRegression()
malli.fit(X_train, y_train)

#Mallin mukaisten ennusteiden laskeminen opetusdatalle ja testidatalle:
y_train_malli = malli.predict(X_train)
y_test_malli = malli.predict(X_test)

C:\Users\Oem\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Oem\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [16]:
#Oikeaan osuneiden ennusteiden osuus datoissa
as_train = accuracy_score(y_train, y_train_malli)
as_test = accuracy_score(y_test, y_test_malli)

#Confusion-matriisit datoille
cm_train = confusion_matrix(y_train, y_train_malli)
cm_test = confusion_matrix(y_test, y_test_malli)

print('Oikeaan osuneiden ennusteiden osuus opetusdatassa = {}'.format(as_train))
print('Confusion-matriisi opetusdatalle = \n {}'.format(cm_train) + "\n")
print('Oikeaan osuneiden ennusteiden osuus testidatassa = {}'.format(as_test))
print('Confusion-matriisi testidatalle = \n {}'.format(cm_test))

Oikeaan osuneiden ennusteiden osuus opetusdatassa = 0.9849624060150376
Confusion-matriisi opetusdatalle = 
 [[39  1  0]
 [ 0 56  1]
 [ 0  0 36]]

Oikeaan osuneiden ennusteiden osuus testidatassa = 0.9111111111111111
Confusion-matriisi testidatalle = 
 [[18  1  0]
 [ 1 12  1]
 [ 0  1 11]]


Logistinen regressio onnistuu ennustamaan opetusdatan lähes täydellisesti ja testidatan melko hyvin: 91% 

In [17]:
malli.predict_proba(X)

array([[9.95323697e-01, 3.90104826e-03, 7.75254834e-04],
       [9.97335966e-01, 2.03598191e-03, 6.28051921e-04],
       [9.98412647e-01, 2.65606641e-04, 1.32174608e-03],
       [9.95992536e-01, 1.68260525e-07, 4.00729565e-03],
       [8.08999330e-02, 9.11456726e-01, 7.64334142e-03],
       [9.97860422e-01, 1.53420119e-06, 2.13804330e-03],
       [9.98939634e-01, 8.56246427e-05, 9.74741160e-04],
       [9.97630298e-01, 2.57488627e-04, 2.11221380e-03],
       [9.94427797e-01, 4.58564505e-03, 9.86558049e-04],
       [9.90011271e-01, 7.83767683e-05, 9.91035270e-03],
       [9.99540432e-01, 8.79402885e-06, 4.50773917e-04],
       [9.97337606e-01, 3.22984608e-04, 2.33940924e-03],
       [9.97672496e-01, 2.82909323e-05, 2.29921266e-03],
       [9.99199079e-01, 6.58840468e-04, 1.42080454e-04],
       [9.99023847e-01, 5.84061998e-08, 9.76094290e-04],
       [9.70519224e-01, 2.04403467e-06, 2.94787320e-02],
       [9.94695300e-01, 1.60914258e-04, 5.14378591e-03],
       [9.89984361e-01, 4.55317

Ensimmäinen 99,532 % todennäköisyydellä viini1,  0,390 % todennäköisyydellä viini2 ja 0,0775 % todennäköisyydellä viini3.

In [18]:
#Uusi dataframe
df4=pd.read_excel('http://taanila.fi/wine.xlsx')
df4.rename(columns={'Y':'Viini'}, inplace=True)

In [19]:
#Tehdään fature-matriisi,jota varten pudotetaan Y-muuttuja
X = df4.drop('Viini', axis=1)

#Tehdään target eli viini
y = df4['Viini']

In [20]:
#jaetaan data uudestaan testidataan ja opetusdataan
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5)

In [21]:
#Sovitetaan opetusdata ja testidata päätöspuu-malliin
malli = tree.DecisionTreeClassifier(max_depth=3)
malli.fit(X_train, y_train)

#Mallin mukaisten ennusteiden laskeminen opetusdatalle ja testidatalle:
y_train_malli = malli.predict(X_train)
y_test_malli = malli.predict(X_test)

In [22]:
#Oikeaan osuneiden ennusteiden osuus datoissa
as_train = accuracy_score(y_train, y_train_malli)
as_test = accuracy_score(y_test, y_test_malli)

#Confusion-matriisit datoille
cm_train = confusion_matrix(y_train, y_train_malli)
cm_test = confusion_matrix(y_test, y_test_malli)

print('Oikeaan osuneiden ennusteiden osuus opetusdatassa = {}'.format(as_train))
print('Confusion-matriisi opetusdatalle = \n {}'.format(cm_train) + "\n")
print('Oikeaan osuneiden ennusteiden osuus testidatassa = {}'.format(as_test))
print('Confusion-matriisi testidatalle = \n {}'.format(cm_test))

Oikeaan osuneiden ennusteiden osuus opetusdatassa = 1.0
Confusion-matriisi opetusdatalle = 
 [[40  0  0]
 [ 0 57  0]
 [ 0  0 36]]

Oikeaan osuneiden ennusteiden osuus testidatassa = 0.9111111111111111
Confusion-matriisi testidatalle = 
 [[17  2  0]
 [ 1 12  1]
 [ 0  0 12]]


Max depth 3 antaa antaa jo parhaimman tuloksen mihin malli pystyy. Päätöspuu ennustaa opetusdatan täydellisesti ja testi datan melko hyvin: 91%

In [23]:
#Uusi dataframe
df5=pd.read_excel('http://taanila.fi/wine.xlsx')
df5.rename(columns={'Y':'Viini'}, inplace=True)

In [24]:
#Tehdään fature-matriisi,jota varten pudotetaan Y-muuttuja
X = df5.drop('Viini', axis=1)

In [25]:
#Sovitetaan opetusdata ja testidata päätöspuu-malliin
malli = KMeans(n_clusters=3)
malli.fit(X)

#Ryhmien keskukset (sepal_length, sepal_width, petal_length, petal_width):
malli.cluster_centers_

array([[1.25166667e+01, 2.49420290e+00, 2.28855072e+00, 2.08231884e+01,
        9.23478261e+01, 2.07072464e+00, 1.75840580e+00, 3.90144928e-01,
        1.45188406e+00, 4.08695651e+00, 9.41159420e-01, 2.49072464e+00,
        4.58231884e+02],
       [1.38044681e+01, 1.88340426e+00, 2.42617021e+00, 1.70234043e+01,
        1.05510638e+02, 2.86723404e+00, 3.01425532e+00, 2.85319149e-01,
        1.91042553e+00, 5.70255319e+00, 1.07829787e+00, 3.11404255e+00,
        1.19514894e+03],
       [1.29298387e+01, 2.50403226e+00, 2.40806452e+00, 1.98903226e+01,
        1.03596774e+02, 2.11112903e+00, 1.58403226e+00, 3.88387097e-01,
        1.50338710e+00, 5.65032258e+00, 8.83967742e-01, 2.36548387e+00,
        7.28338710e+02]])

In [26]:
#Ryhmiin kuulumiset:
X['K'] = malli.predict(X)
pd.crosstab(X['K'], 'lkm')

col_0  lkm
K         
0       69
1       47
2       62

In [27]:
#Tunnuslukuja ryhmittäin:
X.groupby('K').describe().T.style.format('{:.1f}')

In [39]:
#Katsotaan miten muodostetut ryhmät suhteutuava lajikkeisiin:
pd.crosstab(X['K'], df['Viini'])

Viini   1   2   3
K                
0       0  50  19
1      46   1   0
2      13  20  29

Ensimmäiseen ryhmään meni suuri määrä kaikkia viinejä, mutta ryhmä vaikuttaisi olevan viini 3. Toinen ryhmä on selkeästi viini 1 ja kolmas ryhmä melko selvästi viini 2